### ISSUE TITLE
where is the listener for on Later click to continue app ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [hummatli/AndroidAppUpdater#5]
whenever i call MAHAndroidupdater.init it works but it suddenly continue to go on next app code. how i can stop other code to contine while i didn't click on later or something like this.

**Comment by hummatli** [comment]
MAHAndroidupdater.init  is for initialization process.  
It sends request to the service to get your app current and minimum version which you have already set on your service and caches it locally.

What do you mean by "next app code"?  
If it's your own code then you have to do your own logic and add listener.

**Comment by ZohaibGhafoor** [comment]
i mean by clicking on later how app start as usual to it's normal behaviour.

**Comment by hummatli** [comment]
Sorry, but I don't understand what do you mean by "clicking on later".  Explain broadly if you can.

Otherwise there is not any listener and if you thing it's true logic you can implement it in your own fork

**Comment by hummatli** [comment]
Hi @ZohaibGhafoor.

If you have not any question about this issue, I am closing it in two days.

Regards, @hummatli

**Comment by ZohaibGhafoor** [comment]
Hello @hummatli 
Sorry for the late reply. Was a little bit busy. yes you can close it because i fork it and work on it manually on my own requirements. thanks.
Regards, @ZohaibGhafoor

**Comment by hummatli** [comment]
Ok @ZohaibGhafoor . I am closing it

Regards @hummatli

**Comment by hummatli** [comment]
Hi Zohaib Ghafoor.

I you are using MAHAndroidUpdater Library and you have time. I want two
things from you

1)I am collecting applications information which uses MAHAndroidUpdater to
add MAHAndroidUpdater in the GitHub list
<https://github.com/hummatli/MAHAndroidUpdater#applications-using-mahandroidupdater>.

    I would like to see your application in the front of the list
<https://github.com/hummatli/MAHAndroidUpdater#applications-using-mahandroidupdater>
 send
your app name, link or submit a pull request.

2) Provide any translation file if you can.


Best regrads, Sattar Hummatli.
